import {sqliteTable,text,integer,real,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const tournaments=sqliteTable('tournaments',{id:text('id').primaryKey(),payload:text('payload').notNull(),published:integer('published').notNull().default(0),updated:text('updated').notNull()},t=>[index('idx_tournaments_published').on(t.published)]);
export const categories=sqliteTable('categories',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull(),name:text('name').notNull(),gender:text('gender'),ageGroup:text('age_group'),sourceUrl:text('source_url').notNull(),totalPlayers:integer('total_players').notNull().default(0),rounds:integer('rounds'),updated:text('updated').notNull(),payload:text('payload')},t=>[index('idx_categories_tournament').on(t.tournamentId)]);
export const players=sqliteTable('players',{id:text('id').primaryKey(),categoryId:text('category_id').notNull(),tournamentId:text('tournament_id').notNull(),snr:text('snr').notNull(),name:text('name').notNull(),fideId:text('fide_id'),rating:integer('rating'),club:text('club'),country:text('country'),gender:text('gender'),ageGroup:text('age_group'),updated:text('updated').notNull()},t=>[index('idx_players_category').on(t.categoryId),index('idx_players_tournament').on(t.tournamentId),index('idx_players_name').on(t.name)]);
export const rankings=sqliteTable('rankings',{playerId:text('player_id').primaryKey(),categoryId:text('category_id').notNull(),rank:integer('rank'),points:real('points'),buchholz:real('buchholz'),sonnebornBerger:real('sonneborn_berger'),performance:integer('performance'),tiesJson:text('ties_json')},t=>[index('idx_rankings_category').on(t.categoryId)]);
export const matches=sqliteTable('matches',{id:text('id').primaryKey(),categoryId:text('category_id').notNull(),playerId:text('player_id').notNull(),playerWhite:text('player_white'),playerBlack:text('player_black'),round:integer('round').notNull(),board:integer('board'),result:text('result'),score:real('score'),color:text('color'),opponentId:text('opponent_id'),opponentName:text('opponent_name')},t=>[index('idx_matches_player').on(t.playerId)]);
export const details=sqliteTable('details',{tid:text('tid').notNull(),pid:text('pid').notNull(),revision:text('revision').notNull(),payload:text('payload').notNull()},t=>[primaryKey({columns:[t.tid,t.pid,t.revision]})]);
export const previews=sqliteTable('previews',{token:text('token').primaryKey(),owner:text('owner').notNull(),payload:text('payload').notNull(),expires:integer('expires').notNull()});
export const locks=sqliteTable('locks',{key:text('key').primaryKey(),until:integer('until').notNull()});
export const logs=sqliteTable('logs',{id:text('id').primaryKey(),created:text('created').notNull(),ok:integer('ok').notNull(),message:text('message').notNull()},t=>[index('idx_logs_created').on(t.created)]);
export const sessions=sqliteTable('admin_sessions',{hash:text('hash').primaryKey(),csrf:text('csrf').notNull(),expires:integer('expires').notNull()});
export const attempts=sqliteTable('auth_attempts',{key:text('key').primaryKey(),count:integer('count').notNull(),reset:integer('reset').notNull()});

